### ISSUE TITLE
Part numbers in BOM for purchased components

### ISSUE THREAD

**Issue by TELunus** [MarginallyClever/sixi#18]
For purchased components part number at source should be a separate column in the bill of materials.

**Comment by TELunus** [comment]
@i-make-robots 
I'm not sure whether the item `NEMA23 with 47:1 planetary gearbox ` from `stepperonline.com` is supposed to be [the L=56mm one](https://www.omc-stepperonline.com/economy-planetary-gearbox/nema-23-stepper-motor-bipolar-l56mm-w-gear-raio-471-planetary-gearbox-23hs22-2804s-pg47.html?mfp=168-gear-ratio%5B46.656%3A1%5D), or [ the L=76mm one](https://www.omc-stepperonline.com/economy-planetary-gearbox/nema-23-stepper-motor-bipolar-l76mm-w-gear-raio-471-planetary-gearbox-23hs30-2804s-pg47.html?mfp=168-gear-ratio%5B46.656%3A1%5D)

**Comment by TELunus** [comment]
There's a similar issue with the `NEMA8 90:1 planetary gearbox `, it could be L=30 or L=38.

**Comment by TELunus** [comment]
vxb.com doesn't seem to have a `bearing 6806-2RZ 30x42x7`, but they've got a bunch of other 30x42x7 bearings that are variations on 6806-2RS.  See http://www.vxb.com/SearchResults.asp?Search=6806-2RZ

**Comment by i-make-robots** [comment]
commit cca7d3f
